SS_COLOR_BASE=210
SS_FZF_COLORS="fg:#cad3f5,bg:#24273a,hl:#ed8796,fg+:#cad3f5,bg+:#363a4f,hl+:#ed8796,info:#c6a0f6,prompt:#c6a0f6,pointer:#f4dbd6,marker:#f4dbd6,spinner:#f4dbd6,header:#ed8796"

# To disable terminal theme set to 0
SS_GLOBAL_THEME=1

SS_THCLR_11="#24273a" # Color 11: Background
SS_THCLR_10="#cad3f5" # Color 10: Foreground

SS_THCLR_0="#494d64"  # Color 0: Black
SS_THCLR_1="#ed8796"  # Color 1: Red
SS_THCLR_2="#a6da95"  # Color 2: Green
SS_THCLR_3="#eed49f"  # Color 3: Yellow
SS_THCLR_4="#8aadf4"  # Color 4: Blue
SS_THCLR_5="#f5bde6"  # Color 5: Magenta
SS_THCLR_6="#8bd5ca"  # Color 6: Cyan
SS_THCLR_7="#b8c0e0"  # Color 7: White
SS_THCLR_8="#5b6078"  # Color 8: Bright Black
