SS_COLOR_BASE=61
SS_FZF_COLORS="fg:#f8f8f2,bg:#282a36,hl:#bd93f9,fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9,info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6,marker:#ff79c6,spinner:#ffb86c,header:#6272a4"

# To disable terminal theme set to 0
SS_GLOBAL_THEME=1

SS_THCLR_11="#282a36" # Color 11: Background
SS_THCLR_10="#f8f8f2" # Color 10: Foreground

SS_THCLR_0="#21222c"  # Color 0: Black
SS_THCLR_1="#ff5555"  # Color 1: Red
SS_THCLR_2="#50fa7b"  # Color 2: Green
SS_THCLR_3="#f1fa8c"  # Color 3: Yellow
SS_THCLR_4="#bd93f9"  # Color 4: Blue
SS_THCLR_5="#ff79c6"  # Color 5: Magenta
SS_THCLR_6="#8be9fd"  # Color 6: Cyan
SS_THCLR_7="#f8f8f2"  # Color 7: White
SS_THCLR_8="#6272a4"  # Color 8: Bright Black
