SS_COLOR_BASE=26
SS_FZF_COLORS="fg:#24292f,bg:#ffffff,hl:#0969da,fg+:#24292f,bg+:#f6f8fa,hl+:#0969da,info:#57606a,prompt:#0969da,pointer:#0969da,marker:#1a7f37,spinner:#8250df,header:#0969da"

# To disable terminal theme set to 0
SS_GLOBAL_THEME=1

SS_THCLR_11="#ffffff" # Color 11: Background
SS_THCLR_10="#24292f" # Color 10: Foreground

SS_THCLR_0="#24292f"  # Color 0: Black
SS_THCLR_1="#cf222e"  # Color 1: Red
SS_THCLR_2="#1a7f37"  # Color 2: Green
SS_THCLR_3="#9a6700"  # Color 3: Yellow
SS_THCLR_4="#0969da"  # Color 4: Blue
SS_THCLR_5="#8250df"  # Color 5: Magenta
SS_THCLR_6="#1b7c83"  # Color 6: Cyan
SS_THCLR_7="#6e7781"  # Color 7: White
SS_THCLR_8="#8c959f"  # Color 8: Bright Black
