SS_COLOR_BASE=73
SS_FZF_COLORS="fg:#90a4ae,bg:#fafafa,hl:#e53935,fg+:#546e7a,bg+:#e7e7e8,hl+:#e53935,info:#f6a434,prompt:#39adb5,pointer:#7e57c2,marker:#91b859,spinner:#e53935,header:#39adb5"

# To disable terminal theme set to 0
SS_GLOBAL_THEME=1

SS_THCLR_11="#fafafa" # Color 11: Background
SS_THCLR_10="#90a4ae" # Color 10: Foreground

SS_THCLR_0="#e7e7e8"  # Color 0: Black
SS_THCLR_1="#e53935"  # Color 1: Red
SS_THCLR_2="#91b859"  # Color 2: Green
SS_THCLR_3="#f6a434"  # Color 3: Yellow
SS_THCLR_4="#39adb5"  # Color 4: Blue
SS_THCLR_5="#7e57c2"  # Color 5: Magenta
SS_THCLR_6="#39adb5"  # Color 6: Cyan
SS_THCLR_7="#90a4ae"  # Color 7: White
SS_THCLR_8="#b0bec5"  # Color 8: Bright Black
